### PR TITLE
Feature/mg carpet requirejs deps

### PR DESCRIPTION
**Pull request by mateuszgachowski**
Carpet.js prototype of dependencies
- Able to work similar to require.js with async components
- Can be easily shimmed like for example jQuery

Sample use:

``` js
Carpet.module('require-module', ['modules/test'], function (exports, settings, context, deps) {
  'use strict';
  exports.init = function () {
    console.log(deps); // => [{test: 1}]
  };
});
```

``` js
modules/test:
define(function () {
  return {
    'test': 1
  };
});
```

requirejs

### CODE REVIEW

**Comment by mateuszgachowski** [comment]
@maciejsmolinski what do you think?

**Comment by yckart** [comment]
I like this idea... However, it makes no sense to me to depend on `require.js`. We should instead handle those dependencies internally.

**Comment by mateuszgachowski** [comment]
Thanks for your comment @yckart.
In fact this is not hard-dependency at all. If carpet does not find `require` or `define` in scope then it automatically loads into window (global).
I'm not sure if I understand what do you mean about 'internally', can you give some example how would you like to have it?

Thanks :)

**Comment by yckart** [comment]
@mateuszgachowski Ough! Haven't looked into the source, just read the title :P

However, I thought about something like this:

```html
<div data-module="myFirstModule"></div>
<div data-module="mySecondModule"></div>
```

```js
Carpet.module('myFirstModule', function (exports, settings, context) {
  exports.init = function () {
    console.log('I will show when a data-module="myFirstModule" will be found in DOM')
  }
})

Carpet.module('mySecondModule', ['myFirstModule'], function (exports, settings, context) {
  exports.init = function () {
    console.log('I will show when a data-module="mySecondModule" and data-module="myFirstModule" will be found in DOM')
  }
})

Carpet.init()
```

That just ends in a thrown error
```js
> Carpet:error
> Carpet:info ["Module: myFirstModule has been autoinited"]
> "I will show when a data-module="myFirstModule" will be found in DOM"
> Carpet:warn ["Module: mySecondModule has not been found"]
```

I would expect to get:
```js
> "I will show when a data-module="myFirstModule" will be found in DOM"
> "I will show when a data-module="mySecondModule" and data-module="myFirstModule" will be found in DOM"
```

**Comment by mateuszgachowski** [comment]
I think this idea was a bit overthought :) Im closing this PR for now.

**Pull request closed without merging**
