### PR TITLE
modify: allow to init only for selected element

### PR DESCRIPTION
**Pull request by sobstel**
More flexibility if you don't want to enable it for whole document or might init modules inside of HTML loaded via Ajax.

### CODE REVIEW

**Comment by maciejsmolinski** [comment]
:+1: regarding the limited scope - this may help with products that already have some frameworks used and someone's migrating slowly to Carpet. I like it.

Regarding the dynamically added content to the DOM Tree, how's that going to work with already initialised modules? Is it going to affect them in any way or keep untouched?

**Comment by sobstel** [comment]
It should not affect them, but it needs to be checked properly.

**Comment by mateuszgachowski** [comment]
I like the idea. It should work the same as reinitiating carpet (double use of `Carpet.init()`).

Please resolve conflicts and write unit tests for this change. If you need any help or have questions don't hesitate to write here.

**Comment by sobstel** [comment]
I'll sort it out next week.

By the way, I would remove init() in fond of riseOfThe~~Clones~~Modules, just because it's cooler:

Rise Of The Clones

**Comment by sobstel** [comment]
@mateuszgachowski Test added.

**Comment by sobstel** [comment]
This build fails at Travis-CI because of some weird Travis local env issues :/

**Comment by yckart** [comment]
@sobstel This fails, because you just forgott to use the new `element` variable as context for `querySelectorAll` ;)

**Comment by sobstel** [comment]
@yckart :flushed:

Fixed. (it did not help with travis though: https://travis-ci.org/mateuszgachowski/Carpet.js/builds/114298923)

**Comment by mateuszgachowski** [comment]
@sobstel I moved those changes with solved conflicts to a feature branch and soon will merge this to master.

Ill try to solve Travis problem soon.

**Pull request closed without merging**
